# Generated by Django 5.1.2 on 2024-10-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_period_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAvailability',
        ),
    ]
